controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (PROTAGONISTA.isHittingTile(CollisionDirection.Bottom)) {
        PROTAGONISTA.vy = -220
    }
    if (controller.right.isPressed()) {
        music.play(music.melodyPlayable(music.pewPew), music.PlaybackMode.UntilDone)
        pause(500)
    } else if (controller.left.isPressed()) {
        music.play(music.melodyPlayable(music.pewPew), music.PlaybackMode.UntilDone)
        pause(500)
    } else if (controller.A.isPressed()) {
        music.play(music.melodyPlayable(music.pewPew), music.PlaybackMode.UntilDone)
    }
    if (controller.down.isPressed()) {
        pause(2000)
        PROTAGONISTA.z = 10
        PROTAGONISTA.vx = 300
    }
})
let PROTAGONISTA: Sprite = null
PROTAGONISTA = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ............f...................
    ...........f2f..................
    ..........f222f.................
    ..........f222f.................
    ..........f222f.................
    ..........f222f.................
    .........fffffff................
    ..........f777f.................
    ...........fff..................
    ...........f6f..................
    ...........f6f..................
    ...........f6f..................
    ..........ff6ff.................
    ..........f7f7f.................
    ..........f777f.................
    ..........f777f.................
    ..........f777f.................
    ...........f7f..................
    .......ffff6f6ffff..............
    ....7ff...ff6ff...ff7...........
    ....77f....f6f....f77...........
    ....f77...f.f.f...77f...........
    ....f...7f7...7f7...f...........
    ...f....777...777....f..........
    ...f.....f.....f.....f..........
    ...f.....f.....f.....f..........
    ..f......f.....f......f.........
    ..f......f.....f......f.........
    `, SpriteKind.Player)
controller.moveSprite(PROTAGONISTA, 100, 0)
tiles.setCurrentTilemap(tilemap`nivel1`)
scene.setBackgroundColor(12)
PROTAGONISTA.ay = 400
PROTAGONISTA.setVelocity(35, 250)
scene.cameraFollowSprite(PROTAGONISTA)
